### ISSUE TITLE
Add an 'active_at' scope in Timelines::Ephemeral

### ISSUE THREAD

**Issue by Craggar** [Craggar/timelines#1]
We want to be able to query what records were active at a given moment in time by a simpler `active_at(datetime)` scope in the Timelines::Ephemeral concern.

For a given date, this should return all records in the collection that have a started_at <= the given datetime AND with either _no ended_at_ or with an ended_at >= the given datetime.

**Comment by metamoni** [comment]
Closed by https://github.com/Craggar/timelines/pull/2
